#!/bin/bash
# basicsubmenustructure - A sample shell script to display menus and submenus on screen https://bash.cyberciti.biz/guide/A_menu_box
# Store menu options selected by the user

. ./setup-vars

INPUT=/tmp/menu.sh.$$
INPUTSUBMENU1=/tmp/submenu1menu.sh.$$

# Storage file for displaying output from main menu and submenu
OUTPUT=/tmp/output.sh.$$
OUTPUTSUBMENU1=/tmp/submenu1output.sh.$$

# get text editor or fall back to vi_editor
vi_editor=${EDITOR-vi}

# trap and delete temp files
trap "rm $OUTPUT;rm $OUTPUTSUBMENU1;rm $INPUTSUBMENU1; rm $INPUT; exit" SIGHUP SIGINT SIGTERM

#
# Purpose - display output using msgbox 
#  $1 -> set msgbox height
#  $2 -> set msgbox width
#  $3 -> set msgbox title
#
function display_output(){
	local h=${1-10}			# box height default 10
	local w=${2-41} 		# box width default 41
	local t=${3-Output} 	# box title 
	dialog --backtitle "Linux Shell Script Tutorial" --title "${t}" --clear --msgbox "$(<$OUTPUT)" ${h} ${w}
}
function display_outputsubmenu1(){
	local h=${1-10}			# box height default 10
	local w=${2-41} 		# box width default 41
	local t=${3-Output} 	# box title 
    #$DIALOG --clear --title "TEXT BOX" "$@" --textbox "$OUTPUTSUBMENU1" 22 77
    $DIALOG --clear --backtitle "Linux sub menu " --title "Output of ${t}"   --textbox "$OUTPUTSUBMENU1" ${h} ${w}

	#dialog --backtitle "Linux sub menu " --title "${t}" --clear --msgbox "$(<$OUTPUTSUBMENU1)" ${h} ${w}
}

#
# Purpose - display current system date & time
#
function show_date(){
	echo "Today is $(date) @ $(hostname -f)." >$OUTPUT
    display_output 6 60 "Date and Time"
}
function do_ls(){
	echo "output  of ls -al gives $(ls -al)." >$OUTPUTSUBMENU1
    display_outputsubmenu1 20 70  "ls -al"
	}
########################################
# Purpose - display submenu linux
########################################
function show_linux_submenu(){
	### display main menu ###
	dialog --clear  --help-button --backtitle "Linux sub menu" \
	--title "[ SUB - M E N U ]" \
	--menu "You can use the UP/DOWN arrow keys, the first \n\
	Choose the TASK" 15 50 4 \
	ls "show output of ls command" \
	df "show output of df command" \
		Exit "Exit to the shell" 2>"${INPUTSUBMENU1}"
    menuitem=$(<"${INPUTSUBMENU1}")
    # make decsion 
	case $menuitem in
		ls) do_ls;;
		df) do_ls;;
		Exit) echo "Bye"; break;;
	esac
}
########################################
# Purpose - main menu
########################################
# set infinite loop
#
while true
do

	### display main menu ###
	$DIALOG --clear --title "TEXT BOX" "$@" --textbox "$tempfile" 22 77

	dialog --clear  --help-button --backtitle "Linux Shell Script Tutorial" \
	--title "[ M A I N - M E N U ]" \
	--menu "You can use the UP/DOWN arrow keys, the first \n\
	letter of the choice as a hot key, or the \n\
	number keys 1-9 to choose an option.\n\
	Choose the TASK" 15 50 4 \
	MENUlinux "Go to Linux submenu" \
	Calendar "Displays a calendar" \
	Editor "Start a text editor" \
	Exit "Exit to the shell" 2>"${INPUT}"

	menuitem=$(<"${INPUT}")

	# make decision 
	case $menuitem in
		MENUlinux) show_linux_submenu;;
		Calendar) show_calendar;;
		Editor) $vi_editor;;
		Exit) echo "Bye"; break;;
	esac

done

# if temp files found, delete them
[ -f $OUTPUT ] && rm $OUTPUT
[ -f $INPUT ] && rm $INPUT
[ -f $OUTPUTSUBMENU1 ] && rm $OUTPUTSUBMENU1
[ -f $INPUTSUBMENU1 ] && rm $INPUTSUBMENU1

